S = 'sp\xc4m'
print(S)
print(S[2])
file = open('unidata.txt', 'w',  encoding='utf-8')
file.write(S)
file.close()
text = open('unidata.txt', encoding='utf8').read()
print(text)
print(len(text))
raw = open('unidata.txt', 'rb').read()
print(raw)
print(len(raw))
print(text.encode('utf-8'))
print(raw.decode('utf-8'))
print(text.encode('latin-1'))
text_utf16 = text.encode('utf-16')
print(text_utf16)
print(len(text.encode('latin-1')), len(text_utf16))
print(text_utf16.decode('utf-16'))
